services:

  frontend-green:
    image: bhavyatank13/blue-green-project/frontend-app:${TAG}
    container_name: frontend-green
    environment:
      - VERSION=${VERSION}
      - ENVIRONMENT=green
    ports:
      - "3002:3000"


  backend-green:
    image: bhavyatank13/blue-green-project/backend-app:${TAG}
    container_name: backend-green
    environment:
      - VERSION=${VERSION}
      - ENVIRONMENT=green
    ports:
      - "5002:5000"